export PS1="\[\033[1;31m\]\u\[\033[1;33m\]@\[\033[1;34m\]fast-data-dev \[\033[1;36m\]\W\[\033[1;0m\] $ "
source /usr/share/bash-completion/bash_completion
source /opt/landoop/tools/share/kafka-autocomplete/kafka
